import { DragDropContext, Draggable, Droppable } from "@hello-pangea/dnd";
import { ChevronDown } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import AIInputBar from "./components/AIInputBar";
import Sidebar from "./components/Sidebar";
import TaskCard from "./components/TaskCard";
import TopBar from "./components/TopBar";
import { taskApi } from "./services/api";

const STATUSES=["TO DO","IN PROGRESS","PAUSED","SUBMITTED","APPROVED"];
const statusDot={"TO DO":"bg-slate-400","IN PROGRESS":"bg-blue-500",PAUSED:"bg-amber-500",SUBMITTED:"bg-violet-500",APPROVED:"bg-emerald-500"};

function App(){
 const[tasks,setTasks]=useState([]);const[search,setSearch]=useState("");const[department,setDepartment]=useState("All Departments");const[loading,setLoading]=useState(true);const[aiLoading,setAiLoading]=useState(false);const[error,setError]=useState("");
 useEffect(()=>{const load=async()=>{try{setTasks(await taskApi.getAll())}catch(e){setError(e.message)}finally{setLoading(false)}};load()},[]);
 const visibleTasks=useMemo(()=>{const term=search.trim().toLowerCase();return term?tasks.filter(t=>t.title.toLowerCase().includes(term)||t.assignee.toLowerCase().includes(term)):tasks},[tasks,search]);
 const handleDragEnd=async({destination,source,draggableId})=>{if(!destination||destination.droppableId===source.droppableId)return;const previous=tasks;const status=destination.droppableId;setTasks(current=>current.map(t=>t._id===draggableId?{...t,status}:t));try{await taskApi.update(draggableId,{status})}catch(e){setTasks(previous);setError(e.message)}};
 const handleEdit=async(task)=>{const title=window.prompt("Task title",task.title);if(title===null||!title.trim())return;const assignee=window.prompt("Assignee",task.assignee);if(assignee===null)return;try{const updated=await taskApi.update(task._id,{title:title.trim(),assignee:assignee.trim()||"Unassigned"});setTasks(c=>c.map(i=>i._id===updated._id?updated:i))}catch(e){setError(e.message)}};
 const handleDelete=async(id)=>{if(!window.confirm("Delete this task?"))return;const previous=tasks;setTasks(c=>c.filter(t=>t._id!==id));try{await taskApi.remove(id)}catch(e){setTasks(previous);setError(e.message)}};
 const handleAICreate=async(prompt)=>{setAiLoading(true);setError("");try{const task=await taskApi.parseWithAI(prompt);setTasks(c=>[task,...c])}catch(e){setError(e.message)}finally{setAiLoading(false)}};
 return <div className="min-h-screen overflow-x-hidden bg-slate-50 text-slate-950"><Sidebar/><TopBar search={search} onSearchChange={setSearch}/><main className="px-3 pb-36 pt-4 sm:px-4 sm:pt-6 md:px-6 lg:ml-64"><div className="mx-auto max-w-[1600px]"><section className="mb-4 flex flex-col gap-3 sm:mb-6 sm:flex-row sm:items-end sm:justify-between sm:gap-4"><div className="min-w-0"><p className="text-xs font-semibold text-violet-600 sm:text-sm">Workspace</p><h1 className="mt-1 text-xl font-bold tracking-tight sm:text-2xl md:text-3xl">Product Development</h1><p className="mt-1 max-w-xl text-xs leading-5 text-slate-500 sm:text-sm">Move work forward and turn natural-language ideas into tasks.</p></div><div className="relative w-full sm:w-auto"><select value={department} onChange={e=>setDepartment(e.target.value)} className="h-11 w-full appearance-none rounded-xl border border-slate-200 bg-white pl-4 pr-10 text-sm font-medium outline-none sm:w-auto"><option>All Departments</option><option disabled>Engineering — add department field to enable</option><option disabled>Design — add department field to enable</option></select><ChevronDown size={16} className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-slate-400"/></div></section>{error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 px-3 py-3 text-xs text-rose-700 sm:mb-5 sm:px-4 sm:text-sm">{error}</div>}{loading?<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500 sm:p-10">Loading tasks...</div>:<DragDropContext onDragEnd={handleDragEnd}><div className="-mx-3 overflow-x-auto px-3 pb-4 [scrollbar-width:none] sm:-mx-4 sm:px-4 md:mx-0 md:px-0"><section className="flex w-max snap-x snap-mandatory gap-3 md:grid md:w-auto md:grid-cols-2 md:gap-4 md:snap-none xl:grid-cols-5">{STATUSES.map(status=>{const columnTasks=visibleTasks.filter(t=>t.status===status);return <div key={status} className="w-[86vw] max-w-[340px] shrink-0 snap-center rounded-2xl bg-slate-100/80 p-3 sm:w-[360px] md:w-auto md:max-w-none"><div className="mb-3 flex items-center gap-2 px-1"><span className={`h-2.5 w-2.5 rounded-full ${statusDot[status]}`}/><h2 className="text-xs font-bold tracking-wide text-slate-700">{status}</h2><span className="rounded-full bg-white px-2 py-0.5 text-[11px] font-semibold text-slate-500">{columnTasks.length}</span></div><Droppable droppableId={status}>{provided=><div ref={provided.innerRef}{...provided.droppableProps} className="min-h-32 space-y-3">{columnTasks.map((task,index)=><Draggable key={task._id} draggableId={task._id} index={index}>{drag=><div ref={drag.innerRef}{...drag.draggableProps}{...drag.dragHandleProps}><TaskCard task={task} onEdit={handleEdit} onDelete={handleDelete}/></div>}</Draggable>)}{provided.placeholder}</div>}</Droppable></div>})}</section></div></DragDropContext>}</div></main><AIInputBar onCreateTask={handleAICreate} loading={aiLoading}/></div>;
}
export default App;
